files:
  - source: /src/Umbraco.Web.UI/umbraco/config/lang/en.xml
    translation: /src/Umbraco.Web.UI/umbraco/config/lang/%two_letters_code%.xml
    translate_attributes: 0
    content_segmentation: 0
    type: webxml
